app = "standby-nowplaying"

[build]

[deploy]
  release_command = "npm run migrate"

[processes]
  api = "node dist/server.js"
  poller = "node dist/poller-main.js"

[[services]]
  processes = ["api"]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
